# Generated by Django 5.0.4 on 2024-04-10 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomRecette', models.CharField(max_length=100)),
                ('incredients', models.TextField(max_length=1000)),
                ('étapes', models.TextField()),
                ('author', models.CharField(max_length=100)),
                ('imageURL', models.URLField(blank=True, null=True)),
            ],
        ),
    ]
