# Generated by Django 5.0.4 on 2024-04-10 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('GestionRecettes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recette',
            old_name='étapes',
            new_name='etapes',
        ),
    ]
