# Generated by Django 5.0.4 on 2024-04-10 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GestionRecettes', '0003_rename_incredients_recette_ingredients'),
    ]

    operations = [
        migrations.AddField(
            model_name='recette',
            name='notes',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
